DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(AUTHORID LONG AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(GENREID LONG AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(BOOKID LONG AUTO_INCREMENT PRIMARY KEY, AUTHORID LONG, GENREID LONG, TITLE VARCHAR(255),
                  FOREIGN KEY(AUTHORID) REFERENCES AUTHOR(AUTHORID) ON DELETE CASCADE,
                  FOREIGN KEY(GENREID) REFERENCES GENRE(GENREID) ON DELETE CASCADE
                  );

DROP TABLE IF EXISTS BOOK_COMMENT;
CREATE TABLE BOOK_COMMENT(BOOK_COMMENT_ID LONG AUTO_INCREMENT PRIMARY KEY, BOOKID LONG, COMMENT VARCHAR(255),
                          FOREIGN KEY(BOOKID) REFERENCES BOOK(BOOKID) ON DELETE CASCADE
                          );

INSERT INTO AUTHOR(AUTHORID, NAME) values (1, 'Mark Twain');
INSERT INTO GENRE(GENREID, NAME) values (1, 'Novel');
INSERT INTO BOOK(BOOKID, title, AUTHORID, GENREID) values(1, 'Tom Sawyer', 1, 1);