application:
  locale: ru_RU

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true